//  const fs = require('fs')
const validate = require('validator')

//fs.appendFileSync('logfile.txt','System is running!')
//fs.appendFileSync('logfile.txt','System is running!')
//fs.appendFileSync('logfile.txt','System is running!')
//fs.appendFileSync('logfile.txt','System is running!')
//fs.appendFileSync('logfile.txt','System is running!')
//fs.appendFileSync('logfile.txt','System is running!')
//fs.appendFileSync('logfile.txt','System is running!')
//fs.appendFileSync('logfile.txt','System is running!')
//fs.appendFileSync('logfile.txt','System is running!')
//fs.appendFileSync('logfile.txt','System is running!')
//fs.appendFileSync('logfile.txt','System is running!')
//fs.appendFileSync('logfile.txt','System is running!')
//fs.appendFileSync('logfile.txt','System is running!')
//fs.appendFileSync('logfile.txt','System is running!')
//fs.appendFileSync('logfile.txt','System is running!')
//fs.appendFileSync('logfile.txt','System is running!')
//fs.appendFileSync('logfile.txt','System is running!')
//fs.appendFileSync('logfile.txt','System is running!')

console.log(validate.isEmail('www.facebook.com'))
